create database Ecommerce_Sales_Analysis;

select * from ecommerce_sales_analysis;

#1. Who are the top 5 customers based on their total spending (Sales)?
SELECT customer_name, SUM(sales) AS Total_Spent
from ecommerce_sales_analysis
GROUP BY customer_name
ORDER BY Total_Spent DESC
LIMIT 5;

#2. Which product category has generated the highest total sales?
SELECT category, SUM(sales) AS Total_Sales 
FROM ecommerce_sales_analysis 
GROUP BY category 
ORDER BY Total_Sales DESC 
LIMIT 1;

#3.What is the total revenue and profit generated by each payment mode?
SELECT payment_mode, 
       ROUND(SUM(sales), 2) AS Total_Sales, 
       ROUND(SUM(profit), 2) AS Total_Profit
FROM ecommerce_sales_analysis
GROUP BY payment_mode
ORDER BY Total_Sales DESC;

#4. Which top 5 cities have the highest volume (Quantity) of products ordered?
SELECT city, SUM(quantity) AS Total_Quantity
FROM ecommerce_sales_analysis
GROUP BY city
ORDER BY Total_Quantity DESC
LIMIT 5;

#5. Which month and year recorded the highest total sales?
SELECT DATE_FORMAT(order_date, '%Y-%m') AS Month, 
       ROUND(SUM(sales),2) AS Monthly_Revenue
FROM ecommerce_sales_analysis
GROUP BY Month
ORDER BY Monthly_Revenue DESC
LIMIT 1;

#6. What is the average sales amount per order for each City?
SELECT city , ROUND(AVG(sales),2) AS Average_Order_Value 
FROM ecommerce_sales_analysis
GROUP BY city 
ORDER BY Average_Order_Value DESC;

#7. Find the total profit for each month in the year 2024.
SELECT MONTH(order_date) AS Sale_Month, ROUND(SUM(sales), 2) AS Monthly_Profit 
FROM ecommerce_sales_analysis 
WHERE YEAR(order_date) = 2024 
GROUP BY Sale_Month 
ORDER BY Sale_Month;

#8. Which 'Product Name' has been sold the most in terms of total quantity?
SELECT product_name, SUM(quantity) AS Total_Qty_Sold 
from ecommerce_sales_analysis
GROUP BY Product_Name 
ORDER BY Total_Qty_Sold DESC 
LIMIT 1;

#9. Calculate the profit margin percentage for each region and sort by the highest margin.
SELECT region, 
       ROUND((SUM(profit) / SUM(sales)),3) * 100 AS Profit_Margin_Percentage 
from ecommerce_sales_analysis 
GROUP BY region 
ORDER BY Profit_Margin_Percentage DESC;

#10.Calculate total sales based on the day of the week.
SELECT DAYNAME(order_date) AS Day_of_Week, 
       ROUND(SUM(sales), 2) AS Total_Sales
FROM ecommerce_sales_analysis
GROUP BY Day_of_Week
ORDER BY Total_Sales DESC;